### ISSUE TITLE
Accuracy is hard to reach

### ISSUE THREAD

**Issue by AAAdecade** [anhphan2705/mmseg_pidnet#1]
Hello！
Thank you for your excellent work and analysis
Can you reproduce the PIDNet results with the same accuracy as the original version in the cityscapes test set 78.6? Why is my val 78.4 test 77.0?
Looking forward to your answer, thank you！

**Comment by anhphan2705** [comment]
It is quite hard to get. I have not been able to reproduce the IOU that the paper stated.

**Comment by AAAdecade** [comment]
> 这很难得到。我无法复制论文所述的 IOU。
Thanks for your reply
